### ISSUE TITLE
crypto missing

### ISSUE THREAD

**Issue by goors** [3d0c/skeleton#1]
I am new to go. I do not have crypto installed:

$GOROOT/src/pkg/crypto/tls/generate_cert.go 
$GOROOT is ok. I just need this other part.

Can you help?

**Comment by 3d0c** [comment]
Hi. Looks like the path changed. Please check out GOROOT/src/crypto/tls/generate_cert.go

**Comment by goors** [comment]
it is in /usr/local/go/src/crypto/tls/generate_cert.go. thanks.
